export const PERMISSIONS = {
  TASK_CREATE: 'task:create',
  TASK_READ: 'task:read',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',
  AUDIT_READ: 'audit:read',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  Owner: [PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_READ, PERMISSIONS.TASK_UPDATE, PERMISSIONS.TASK_DELETE, PERMISSIONS.AUDIT_READ],
  Admin: [PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_READ, PERMISSIONS.TASK_UPDATE, PERMISSIONS.TASK_DELETE, PERMISSIONS.AUDIT_READ],
  Viewer: [PERMISSIONS.TASK_READ],
};
